/* eslint-disable */

type __WebviewWindow__ =
  | import("@tauri-apps/api/webview").Webview
  | import("@tauri-apps/api/window").Window;

type __EventObj__<T> = {
  listen: (cb: (event: { payload: T }) => void) => Promise<() => void>;
  once: (cb: (event: { payload: T }) => void) => Promise<() => void>;
  emit: T extends null ? () => Promise<void> : (payload: T) => Promise<void>;
};

export type EventsShape<T extends Record<string, any>> = {
  [K in keyof T]: __EventObj__<T[K]> & {
    (handle: __WebviewWindow__): __EventObj__<T[K]>;
  };
};

export function makeLiveEvent<T extends Record<string, any>>(ev: EventsShape<T>) {
  return function liveEvent<K extends keyof T>(key: K) {
    return (handler: (payload: T[K]) => void) => {
      const obj = ev[key] as __EventObj__<T[K]>;
      return obj.listen((e) => handler(e.payload));
    };
  };
}

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	exists: (path: string) => typedError<boolean, string>(__TAURI_INVOKE("exists", { path })),
	appReady: () => __TAURI_INVOKE<void>("app_ready"),
	resetDevDatabaseAndRestart: () => typedError<null, string>(__TAURI_INVOKE("reset_dev_database_and_restart")),
	getMouseAndWindowPosition: () => typedError<MouseWindowInfo, string>(__TAURI_INVOKE("get_mouse_and_window_position")),
	getWindowKind: () => __TAURI_INVOKE<WindowKindInfo>("get_window_kind"),
	warmWindow: (name: WindowName) => __TAURI_INVOKE<void>("warm_window", { name }),
	coldWindow: (name: WindowName) => __TAURI_INVOKE<boolean>("cold_window", { name }),
	prewarmWindow: (name: WindowName) => __TAURI_INVOKE<void>("prewarm_window", { name }),
	discardPrewarmWindow: (name: WindowName) => __TAURI_INVOKE<boolean>("discard_prewarm_window", { name }),
	recordRendererBootstrapReady: () => __TAURI_INVOKE<void>("record_renderer_bootstrap_ready"),
	createWindow: (name: WindowName, options: {
	width: number | null,
	height: number | null,
} | null) => __TAURI_INVOKE<void>("create_window", { name, options }),
	runBunHelloSidecar: (input: string | null) => typedError<BunSidecarOutput, string>(__TAURI_INVOKE("run_bun_hello_sidecar", { input })),
	getMetaInfo: () => typedError<{
	save_path: string | null,
} | null, string>(__TAURI_INVOKE("get_meta_info")),
	saveMetaInfo: (meta: MetaInfo) => typedError<MetaInfo, string>(__TAURI_INVOKE("save_meta_info", { meta })),
	checkList: () => typedError<boolean, string>(__TAURI_INVOKE("check_list")),
	listCollections: () => typedError<Collection[], string>(__TAURI_INVOKE("list_collections")),
	listPlaylists: () => typedError<PlayList[], string>(__TAURI_INVOKE("list_playlists")),
	getCollection: (url: string) => typedError<{
	name: string,
	url: string,
	folder: string,
	musics: Music[],
	last_updated: string,
	enable_updates: boolean | null,
} | null, string>(__TAURI_INVOKE("get_collection", { url })),
	getPlaylist: (name: string) => typedError<{
	name: string,
	collections: Collection[],
	groups: Group[],
	created_at: AutoFill,
} | null, string>(__TAURI_INVOKE("get_playlist", { name })),
	deletePlaylist: (name: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_playlist", { name })),
	upsertPlaylist: (previousName: string | null, playlist: PlayList) => typedError<PlayList, string>(__TAURI_INVOKE("upsert_playlist", { previousName, playlist })),
	setCollectionUpdates: (url: string, enabled: boolean) => typedError<{
	name: string,
	url: string,
	folder: string,
	musics: Music[],
	last_updated: string,
	enable_updates: boolean | null,
} | null, string>(__TAURI_INVOKE("set_collection_updates", { url, enabled })),
	updateMusicAlias: (url: string, start: number, end: number, alias: string) => typedError<{
	name: string,
	alias: string,
	group: Group,
	url: string,
	path: string | null,
	start: number,
	end: number,
} | null, string>(__TAURI_INVOKE("update_music_alias", { url, start, end, alias })),
	addExclude: (music: Music) => typedError<Exclude, string>(__TAURI_INVOKE("add_exclude", { music })),
	removeExclude: (music: Music) => typedError<boolean, string>(__TAURI_INVOKE("remove_exclude", { music })),
	playPlaylist: (name: string) => typedError<PlayPlaylistSession, string>(__TAURI_INVOKE("play_playlist", { name })),
	setPlaybackContinuationMode: (mode: PlaybackContinuationMode) => typedError<null, string>(__TAURI_INVOKE("set_playback_continuation_mode", { mode })),
	stopPlayback: () => typedError<boolean, string>(__TAURI_INVOKE("stop_playback")),
	getPlaybackStatus: () => typedError<{
	path: string | null,
	playing: boolean,
	paused: boolean,
	position_ms: number,
	duration_ms: number | null,
} | null, string>(__TAURI_INVOKE("get_playback_status")),
	analyzeTrackWaveform: (filePath: string, start: number | null, end: number | null) => typedError<TrackWaveform, string>(__TAURI_INVOKE("analyze_track_waveform", { filePath, start, end })),
	prepareTrackWaveform: (filePath: string, start: number | null, end: number | null) => typedError<TrackWaveformSummary, string>(__TAURI_INVOKE("prepare_track_waveform", { filePath, start, end })),
	getTrackWaveformTile: (filePath: string, start: number | null, end: number | null, pixelsPerSecond: number, tileStartPx: number, tileWidth: number) => typedError<TrackWaveformTile, string>(__TAURI_INVOKE("get_track_waveform_tile", { filePath, start, end, pixelsPerSecond, tileStartPx, tileWidth })),
	enqueueCollectionDownload: (url: string) => typedError<EnqueuedCollectionDownload, string>(__TAURI_INVOKE("enqueue_collection_download", { url })),
	probeDownloadResource: (url: string) => typedError<DownloadResourceProbe, string>(__TAURI_INVOKE("probe_download_resource", { url })),
	resolvePastedDownloadUrl: (url: string) => typedError<PastedDownloadUrlResolution, string>(__TAURI_INVOKE("resolve_pasted_download_url", { url })),
	resumeDownloadTask: (taskId: string) => typedError<DownloadTask, string>(__TAURI_INVOKE("resume_download_task", { taskId })),
	getDownloadTask: (taskId: string) => typedError<DownloadTask, string>(__TAURI_INVOKE("get_download_task", { taskId })),
	listDownloadTasks: () => typedError<DownloadTask[], string>(__TAURI_INVOKE("list_download_tasks")),
};

/** Events */
export const events = {
	fullScreenEvent: makeEvent<FullScreenEvent>("full-screen-event"),
	nowPlayingTrackChangedEvent: makeEvent<NowPlayingTrackChangedEvent>("now-playing-track-changed-event"),
};

/* Types */
/**
 *  Opaque appdb-managed scalar used by `#[fill(...)]` fields.
 * 
 *  The field stays pending until the Store write pipeline resolves it into a
 *  concrete token such as the current timestamp.
 */
export type AutoFill = string | null;

export type BunSidecarOutput = {
	ok: boolean,
	status: number | null,
	stdout: string,
	stderr: string,
};

export type Collection = {
	name: string,
	url: string,
	folder: string,
	musics: Music[],
	last_updated: string,
	enable_updates: boolean | null,
};

export type CollectionSourceKind = "single" | "list";

export type CreateWindowOptions = {
	width: number | null,
	height: number | null,
};

export type DownloadLeaf = {
	id: Id,
	url: string,
	title: string | null,
	file_name: string | null,
	relative_path: string | null,
	duration_seconds: number | null,
	chapter_count: number | null,
	downloaded_bytes: number | null,
	total_bytes: number | null,
	speed_bytes_per_second: number | null,
	eta_seconds: number | null,
	status: DownloadLeafStatus,
	last_error: string | null,
	sequence: number,
	created_at: string,
	updated_at: string,
};

export type DownloadLeafStatus = "queued" | "probing" | "downloading" | "persisting" | "completed" | "failed" | "cancelled" | "interrupted";

export type DownloadResourceProbe = {
	url: string,
	source_kind: CollectionSourceKind,
	title: string,
	item_count: number,
	collection_folder: string,
	enable_updates: boolean | null,
};

export type DownloadTask = {
	id: Id,
	url: string,
	collection_url: string | null,
	collection_name: string | null,
	collection_folder: string | null,
	source_kind: CollectionSourceKind | null,
	trigger: DownloadTrigger,
	status: DownloadTaskStatus,
	leafs: DownloadLeaf[],
	total_leaves: number,
	completed_leaves: number,
	failed_leaves: number,
	last_error: string | null,
	created_at: string,
	updated_at: string,
};

export type DownloadTaskStatus = "queued" | "resolving" | "downloading" | "persisting" | "completed" | "completed_with_errors" | "failed" | "cancelled" | "interrupted";

export type DownloadTrigger = "manual" | "auto_update";

export type EnqueuedCollectionDownload = {
	task: DownloadTask,
	collection: Collection,
};

export type Exclude = {
	music: Music,
	created_at: AutoFill,
};

export type FullScreenEvent = {
	is_fullscreen: boolean,
};

export type Group = {
	name: string,
	url: string,
	folder: string,
};

// Application-facing id type that accepts either string or integer ids.
export type Id = 
// String record key.
({ String: string }) & { Number?: never } | 
// Integer record key.
({ Number: number }) & { String?: never };

export type MetaInfo = {
	save_path: string | null,
};

export type MouseWindowInfo = {
	mouse_x: number,
	mouse_y: number,
	window_x: number,
	window_y: number,
	window_width: number,
	window_height: number,
	rel_x: number,
	rel_y: number,
	pixel_ratio: number,
};

export type Music = {
	name: string,
	alias: string,
	group: Group,
	url: string,
	path: string | null,
	start: number,
	end: number,
};

export type NowPlayingTrackChangedEvent = {
	playlist_name: string,
	music_name: string,
	music_url: string,
	file_path: string,
	start: number,
	end: number,
};

export type PastedDownloadUrlResolution = {
	status: PastedDownloadUrlResolutionStatus,
	url: string | null,
	error: string | null,
	collection: Collection | null,
};

export type PastedDownloadUrlResolutionStatus = "invalid_url" | "existing_collection" | "new_url";

export type PlayList = {
	name: string,
	collections: Collection[],
	groups: Group[],
	created_at: AutoFill,
};

export type PlayPlaylistSession = {
	playlist_name: string,
	track_count: number,
};

export type PlaybackContinuationMode = "random" | "repeatCurrent";

export type PlaybackStatusPayload = {
	path: string | null,
	playing: boolean,
	paused: boolean,
	position_ms: number,
	duration_ms: number | null,
};

export type TrackWaveform = {
	sample_rate: number,
	samples_per_point: number,
	points_per_second: number,
	start_ms: number,
	duration_ms: number,
	peaks: WaveformPeak[],
};

export type TrackWaveformSummary = {
	cache_key: string,
	sample_rate: number,
	samples_per_point: number,
	base_points_per_second: number,
	chunk_duration_ms: number,
	start_ms: number,
	duration_ms: number,
	levels: number[],
};

export type TrackWaveformTile = {
	start_px: number,
	width_px: number,
	points_per_second: number,
	min: number[],
	max: number[],
};

export type WaveformPeak = {
	min: number,
	max: number,
};

export type WindowKindInfo = {
	window: WindowName | null,
	label: string,
	is_primary_window: boolean,
	is_user_window: boolean,
	is_prepared_window: boolean,
};

export type WindowName = "Main" | "Support";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

