/* eslint-disable */

type __WebviewWindow__ =
  | import("@tauri-apps/api/webview").Webview
  | import("@tauri-apps/api/window").Window;

type __EventObj__<T> = {
  listen: (cb: (event: { payload: T }) => void) => Promise<() => void>;
  once: (cb: (event: { payload: T }) => void) => Promise<() => void>;
  emit: T extends null ? () => Promise<void> : (payload: T) => Promise<void>;
};

export type EventsShape<T extends Record<string, any>> = {
  [K in keyof T]: __EventObj__<T[K]> & {
    (handle: __WebviewWindow__): __EventObj__<T[K]>;
  };
};

export function makeLiveEvent<T extends Record<string, any>>(ev: EventsShape<T>) {
  return function liveEvent<K extends keyof T>(key: K) {
    return (handler: (payload: T[K]) => void) => {
      const obj = ev[key] as __EventObj__<T[K]>;
      return obj.listen((e) => handler(e.payload));
    };
  };
}

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	exists: (path: string) => typedError<boolean, string>(__TAURI_INVOKE("exists", { path })),
	appReady: () => __TAURI_INVOKE<void>("app_ready"),
	recordPlaylistBootstrapReady: () => __TAURI_INVOKE<void>("record_playlist_bootstrap_ready"),
	resetDevDatabaseAndRestart: () => typedError<null, string>(__TAURI_INVOKE("reset_dev_database_and_restart")),
	getMouseAndWindowPosition: () => typedError<MouseWindowInfo, string>(__TAURI_INVOKE("get_mouse_and_window_position")),
	getWindowKind: () => __TAURI_INVOKE<WindowKindInfo>("get_window_kind"),
	warmWindow: (name: WindowName) => __TAURI_INVOKE<void>("warm_window", { name }),
	coldWindow: (name: WindowName) => __TAURI_INVOKE<boolean>("cold_window", { name }),
	prewarmWindow: (name: WindowName) => __TAURI_INVOKE<void>("prewarm_window", { name }),
	discardPrewarmWindow: (name: WindowName) => __TAURI_INVOKE<boolean>("discard_prewarm_window", { name }),
	recordRendererBootstrapReady: () => __TAURI_INVOKE<void>("record_renderer_bootstrap_ready"),
	createWindow: (name: WindowName, options: {
	width: number | null,
	height: number | null,
} | null) => __TAURI_INVOKE<void>("create_window", { name, options }),
	runBunHelloSidecar: (input: string | null) => typedError<BunSidecarOutput, string>(__TAURI_INVOKE("run_bun_hello_sidecar", { input })),
	getMetaInfo: () => typedError<{
	save_path: string | null,
} | null, string>(__TAURI_INVOKE("get_meta_info")),
	saveMetaInfo: (meta: MetaInfo) => typedError<MetaInfo, string>(__TAURI_INVOKE("save_meta_info", { meta })),
	checkList: () => typedError<boolean, string>(__TAURI_INVOKE("check_list")),
	listCollections: () => typedError<Collection[], string>(__TAURI_INVOKE("list_collections")),
	listPlaylists: () => typedError<PlayListListView[], string>(__TAURI_INVOKE("list_playlists")),
	claimGeneratedPlaylistName: (seedNames: string[]) => typedError<string, string>(__TAURI_INVOKE("claim_generated_playlist_name", { seedNames })),
	listConfigLibrary: () => typedError<ConfigLibraryView, string>(__TAURI_INVOKE("list_config_library")),
	getCollection: (url: string) => typedError<{
	name: string,
	url: string,
	folder: string,
	musics: Music[],
	last_updated: string,
	enable_updates: boolean | null,
} | null, string>(__TAURI_INVOKE("get_collection", { url })),
	getPlaylist: (name: string) => typedError<{
	name: string,
	collections: Collection[],
	groups: Group[],
	extra: Music[],
	created_at: AutoFill,
} | null, string>(__TAURI_INVOKE("get_playlist", { name })),
	getPlaylistConfig: (name: string) => typedError<{
	name: string,
	collections: CollectionSurfaceView[],
	groups: GroupSurfaceView[],
	extra: Music[],
	created_at: AutoFill,
} | null, string>(__TAURI_INVOKE("get_playlist_config", { name })),
	deletePlaylist: (name: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_playlist", { name })),
	upsertPlaylist: (previousName: string | null, playlist: PlayListWriteRequest) => typedError<PlayListListView, string>(__TAURI_INVOKE("upsert_playlist", { previousName, playlist })),
	pushExtra: (name: string, music: Music) => typedError<{
	name: string,
	collections: CollectionSurfaceView[],
	groups: GroupSurfaceView[],
	extra: Music[],
	created_at: AutoFill,
} | null, string>(__TAURI_INVOKE("push_extra", { name, music })),
	removeExtra: (name: string, music: Music) => typedError<{
	name: string,
	collections: CollectionSurfaceView[],
	groups: GroupSurfaceView[],
	extra: Music[],
	created_at: AutoFill,
} | null, string>(__TAURI_INVOKE("remove_extra", { name, music })),
	setCollectionUpdates: (url: string, enabled: boolean) => typedError<{
	name: string,
	url: string,
	folder: string,
	musics: Music[],
	last_updated: string,
	enable_updates: boolean | null,
} | null, string>(__TAURI_INVOKE("set_collection_updates", { url, enabled })),
	updateMusic: (url: string, startMs: number, endMs: number, alias: string, nextStartMs: number, nextEndMs: number) => typedError<{
	occurrence_id?: string,
	name: string,
	alias: string,
	group: Group,
	canonical_music_id: string,
	url: string,
	path: string | null,
	start_ms: number,
	end_ms: number,
	liked: boolean,
	loudness_profile?: LoudnessProfile | null,
} | null, string>(__TAURI_INVOKE("update_music", { url, startMs, endMs, alias, nextStartMs, nextEndMs })),
	setCurrentMusicLiked: (liked: boolean) => typedError<{
	occurrence_id?: string,
	name: string,
	alias: string,
	group: Group,
	canonical_music_id: string,
	url: string,
	path: string | null,
	start_ms: number,
	end_ms: number,
	liked: boolean,
	loudness_profile?: LoudnessProfile | null,
} | null, string>(__TAURI_INVOKE("set_current_music_liked", { liked })),
	createMusic: (sourceCollectionUrl: string, music: Music) => typedError<Music, string>(__TAURI_INVOKE("create_music", { sourceCollectionUrl, music })),
	deleteMusic: (url: string, startMs: number, endMs: number) => typedError<boolean, string>(__TAURI_INVOKE("delete_music", { url, startMs, endMs })),
	listMusicsByFilePath: (filePath: string) => typedError<Music[], string>(__TAURI_INVOKE("list_musics_by_file_path", { filePath })),
	loadSpectrumMusicContext: (filePath: string, sourceUrl: string, sourceStartMs: number, sourceEndMs: number) => typedError<SpectrumMusicContext, string>(__TAURI_INVOKE("load_spectrum_music_context", { filePath, sourceUrl, sourceStartMs, sourceEndMs })),
	addExclude: (music: Music) => typedError<AddExcludeResult, string>(__TAURI_INVOKE("add_exclude", { music })),
	removeExclude: (music: Music) => typedError<RemoveExcludeResult, string>(__TAURI_INVOKE("remove_exclude", { music })),
	createLocalCollectionShell: (collectionPath: string) => typedError<Collection, string>(__TAURI_INVOKE("create_local_collection_shell", { collectionPath })),
	importLocalCollection: (collectionPath: string) => typedError<Collection, string>(__TAURI_INVOKE("import_local_collection", { collectionPath })),
	playPlaylist: (name: string) => typedError<PlayPlaylistSession, string>(__TAURI_INVOKE("play_playlist", { name })),
	excludeCurrentMusicAndSkip: () => typedError<ExcludeCurrentMusicAndSkipResult, string>(__TAURI_INVOKE("exclude_current_music_and_skip")),
	setPlaybackContinuationMode: (mode: PlaybackContinuationMode) => typedError<null, string>(__TAURI_INVOKE("set_playback_continuation_mode", { mode })),
	enterSpectrumPlaybackScope: () => typedError<number, string>(__TAURI_INVOKE("enter_spectrum_playback_scope")),
	exitSpectrumPlaybackScope: (scopeId: number) => typedError<null, string>(__TAURI_INVOKE("exit_spectrum_playback_scope", { scopeId })),
	stopPlayback: () => typedError<boolean, string>(__TAURI_INVOKE("stop_playback")),
	pausePlayback: () => typedError<boolean, string>(__TAURI_INVOKE("pause_playback")),
	resumePlayback: () => typedError<boolean, string>(__TAURI_INVOKE("resume_playback")),
	playSpectrumMusic: (scopeId: number, track: PlaybackTrackPayload, positionMs: number | null) => typedError<boolean, string>(__TAURI_INVOKE("play_spectrum_music", { scopeId, track, positionMs })),
	restoreSpectrumMusic: (scopeId: number, track: PlaybackTrackPayload, positionMs: number | null) => typedError<boolean, string>(__TAURI_INVOKE("restore_spectrum_music", { scopeId, track, positionMs })),
	pauseSpectrumMusic: (scopeId: number) => typedError<boolean, string>(__TAURI_INVOKE("pause_spectrum_music", { scopeId })),
	resumeSpectrumMusic: (scopeId: number, track: PlaybackTrackPayload) => typedError<boolean, string>(__TAURI_INVOKE("resume_spectrum_music", { scopeId, track })),
	updateSpectrumPlaybackLoopSignal: (scopeId: number, payload: SpectrumPlaybackLoopSignalPayload) => typedError<{
	path: string | null,
	playing: boolean,
	paused: boolean,
	position_ms: number,
	duration_ms: number | null,
	playlist_name: string | null,
	music_url: string | null,
	track_start_ms: number | null,
	track_end_ms: number | null,
	playback_start_ms: number | null,
	playback_end_ms: number | null,
} | null, string>(__TAURI_INVOKE("update_spectrum_playback_loop_signal", { scopeId, payload })),
	beginPlaybackSeek: () => typedError<{
	path: string | null,
	playing: boolean,
	paused: boolean,
	position_ms: number,
	duration_ms: number | null,
	playlist_name: string | null,
	music_url: string | null,
	track_start_ms: number | null,
	track_end_ms: number | null,
	playback_start_ms: number | null,
	playback_end_ms: number | null,
} | null, string>(__TAURI_INVOKE("begin_playback_seek")),
	cancelPlaybackSeek: () => typedError<{
	path: string | null,
	playing: boolean,
	paused: boolean,
	position_ms: number,
	duration_ms: number | null,
	playlist_name: string | null,
	music_url: string | null,
	track_start_ms: number | null,
	track_end_ms: number | null,
	playback_start_ms: number | null,
	playback_end_ms: number | null,
} | null, string>(__TAURI_INVOKE("cancel_playback_seek")),
	seekPlayback: (positionMs: number, endMs: number) => typedError<{
	path: string | null,
	playing: boolean,
	paused: boolean,
	position_ms: number,
	duration_ms: number | null,
	playlist_name: string | null,
	music_url: string | null,
	track_start_ms: number | null,
	track_end_ms: number | null,
	playback_start_ms: number | null,
	playback_end_ms: number | null,
} | null, string>(__TAURI_INVOKE("seek_playback", { positionMs, endMs })),
	getPlaybackStatus: () => typedError<{
	path: string | null,
	playing: boolean,
	paused: boolean,
	position_ms: number,
	duration_ms: number | null,
	playlist_name: string | null,
	music_url: string | null,
	track_start_ms: number | null,
	track_end_ms: number | null,
	playback_start_ms: number | null,
	playback_end_ms: number | null,
} | null, string>(__TAURI_INVOKE("get_playback_status")),
	analyzeTrackWaveform: (filePath: string, start: number | null, end: number | null) => typedError<TrackWaveform, string>(__TAURI_INVOKE("analyze_track_waveform", { filePath, start, end })),
	prepareTrackWaveform: (filePath: string, start: number | null, end: number | null) => typedError<TrackWaveformSummary, string>(__TAURI_INVOKE("prepare_track_waveform", { filePath, start, end })),
	getTrackWaveformTile: (filePath: string, start: number | null, end: number | null, pixelsPerSecond: number | null, tileStartPx: number, tileWidth: number) => typedError<TrackWaveformTile, string>(__TAURI_INVOKE("get_track_waveform_tile", { filePath, start, end, pixelsPerSecond, tileStartPx, tileWidth })),
	enqueueCollectionDownload: (url: string) => typedError<EnqueuedCollectionDownload, string>(__TAURI_INVOKE("enqueue_collection_download", { url })),
	resolvePastedDownloadUrl: (url: string) => typedError<PastedDownloadUrlResolution, string>(__TAURI_INVOKE("resolve_pasted_download_url", { url })),
	probeDownloadRootTitle: (url: string) => typedError<DownloadRootTitleEvidence, string>(__TAURI_INVOKE("probe_download_root_title", { url })),
	resumeDownloadTask: (taskId: string) => typedError<DownloadTask, string>(__TAURI_INVOKE("resume_download_task", { taskId })),
	submitYoutubeCookiesAndResumeDownloadTask: (taskId: string, cookies: string) => typedError<DownloadTask, string>(__TAURI_INVOKE("submit_youtube_cookies_and_resume_download_task", { taskId, cookies })),
	getDownloadTask: (taskId: string) => typedError<DownloadTask, string>(__TAURI_INVOKE("get_download_task", { taskId })),
	listDownloadTasks: () => typedError<DownloadTask[], string>(__TAURI_INVOKE("list_download_tasks")),
	getRemoteShareStatus: () => typedError<RemoteShareStatus, string>(__TAURI_INVOKE("get_remote_share_status")),
	setRemoteShareEnabled: (enabled: boolean) => typedError<RemoteShareStatus, string>(__TAURI_INVOKE("set_remote_share_enabled", { enabled })),
	setRemoteShareCode: (code: string) => typedError<RemoteShareStatus, string>(__TAURI_INVOKE("set_remote_share_code", { code })),
};

/** Events */
export const events = {
	downloadTaskChangeSignal: makeEvent<DownloadTaskChangeSignal>("download-task-change-signal"),
	fullScreenEvent: makeEvent<FullScreenEvent>("full-screen-event"),
	hardwareHorizontalWheelEvent: makeEvent<HardwareHorizontalWheelEvent>("hardware-horizontal-wheel-event"),
	nowPlayingTrackChangedEvent: makeEvent<NowPlayingTrackChangedEvent>("now-playing-track-changed-event"),
	nowPlayingTrackLikedChangedEvent: makeEvent<NowPlayingTrackLikedChangedEvent>("now-playing-track-liked-changed-event"),
	playbackAudioVisualizationFrameEvent: makeEvent<PlaybackAudioVisualizationFrameEvent>("playback-audio-visualization-frame-event"),
	playbackDiagnosticTraceEvent: makeEvent<PlaybackDiagnosticTraceEvent>("playback-diagnostic-trace-event"),
	playbackExcludeCommittedEvent: makeEvent<PlaybackExcludeCommittedEvent>("playback-exclude-committed-event"),
	playbackSurfaceStatusChangedEvent: makeEvent<PlaybackSurfaceStatusChangedEvent>("playback-surface-status-changed-event"),
};

/* Types */
export type AddExcludeResult = {
	exclude: Exclude,
	exclude_availability: ExcludeAvailability,
};

/**
 *  Opaque appdb-managed scalar used by `#[fill(...)]` fields.
 * 
 *  The field stays pending until the Store write pipeline resolves it into a
 *  concrete token such as the current timestamp.
 */
export type AutoFill = string | null;

export type BunSidecarOutput = {
	ok: boolean,
	status: number | null,
	stdout: string,
	stderr: string,
};

export type Collection = {
	name: string,
	url: string,
	folder: string,
	musics: Music[],
	last_updated: string,
	enable_updates: boolean | null,
};

export type CollectionGroupMembershipView = {
	collection_url: string,
	group_url: string,
};

export type CollectionGroupOwner = {
	name: string,
	url: string,
	folder: string,
	last_updated: string,
	enable_updates: boolean | null,
};

export type CollectionSourceKind = "single" | "list";

export type CollectionSurfaceView = {
	name: string,
	url: string,
	folder: string,
	last_updated: string,
	enable_updates: boolean | null,
};

export type ConfigLibraryView = {
	collections: CollectionSurfaceView[],
	groups: GroupSurfaceView[],
	collection_group_memberships: CollectionGroupMembershipView[],
	excludes: Exclude[],
	exclude_availability: ExcludeAvailability,
};

export type CreateWindowOptions = {
	width: number | null,
	height: number | null,
};

export type DownloadCredentialRequestSignal = {
	provider: string,
	reason: string,
};

export type DownloadLeaf = {
	id: Id,
	url: string,
	title: string | null,
	file_name: string | null,
	relative_path: string | null,
	group: DownloadLeafGroupContext | null,
	duration_ms: number | null,
	duration_seconds: number | null,
	chapter_count: number | null,
	downloaded_bytes: number | null,
	total_bytes: number | null,
	speed_bytes_per_second: number | null,
	eta_seconds: number | null,
	status: DownloadLeafStatus,
	last_error: string | null,
	sequence: number,
	created_at: string,
	updated_at: string,
};

export type DownloadLeafGroupContext = {
	name: string,
	url: string,
	folder: string,
};

export type DownloadLeafStatus = "queued" | "probing" | "downloading" | "persisting" | "measuring_loudness" | "awaiting_credentials" | "completed" | "failed" | "cancelled" | "interrupted";

export type DownloadRootTitleEvidence = {
	url: string,
	title: string,
	folder: string,
	enable_updates: boolean | null,
	source_kind: CollectionSourceKind,
	collection: Collection,
};

export type DownloadTask = {
	id: Id,
	url: string,
	collection_url: string | null,
	collection_name: string | null,
	collection_folder: string | null,
	source_kind: CollectionSourceKind | null,
	trigger: DownloadTrigger,
	status: DownloadTaskStatus,
	leafs: DownloadLeaf[],
	total_leaves: number,
	completed_leaves: number,
	failed_leaves: number,
	last_error: string | null,
	created_at: string,
	updated_at: string,
};

export type DownloadTaskChangeSignal = {
	task_id: string,
	task_url: string,
	collection_url: string | null,
	collection_name: string | null,
	status: DownloadTaskStatus,
	last_error: string | null,
	credential_request: DownloadCredentialRequestSignal | null,
};

export type DownloadTaskStatus = "queued" | "resolving" | "downloading" | "persisting" | "awaiting_credentials" | "completed" | "completed_with_errors" | "failed" | "cancelled" | "interrupted";

export type DownloadTrigger = "manual" | "local_import" | "auto_update";

export type EnqueuedCollectionDownload = {
	task: DownloadTask,
	collection: Collection | null,
};

export type Exclude = {
	music: Music,
	created_at: AutoFill,
};

export type ExcludeAvailability = {
	fully_excluded_collection_urls: string[],
	fully_excluded_group_urls: string[],
};

export type ExcludeCurrentMusicAndSkipResult = { status: "skipped"; exclude: Exclude; exclude_availability: ExcludeAvailability } | { status: "deleted_playlist"; playlist_name: string; exclude: Exclude; exclude_availability: ExcludeAvailability } | { status: "no_active_track" } | { status: "missing_music" };

export type FullScreenEvent = {
	is_fullscreen: boolean,
};

export type Group = {
	name: string,
	url: string,
	collection: CollectionGroupOwner,
	folder: string,
};

export type GroupSurfaceView = {
	name: string,
	url: string,
	folder: string,
};

export type HardwareHorizontalWheelEvent = {
	client_x: number | null,
	client_y: number | null,
	delta_x: number,
	wheel_delta_unit: number,
	window_label: string,
};

/**  Application-facing id type that accepts either string or integer ids. */
export type Id = 
/**  String record key. */
({ String: string }) & { Number?: never } | 
/**  Integer record key. */
({ Number: number }) & { String?: never };

export type LoudnessProfile = {
	integrated_lufs: number | null,
	true_peak_dbtp?: number | null,
	lra?: number | null,
	short_lufs_p50?: number | null,
	short_lufs_p80?: number | null,
	short_lufs_p95?: number | null,
	short_lufs_max?: number | null,
	presence_db?: number | null,
	model_adjustment_db?: number | null,
};

export type MetaInfo = {
	save_path: string | null,
};

export type MouseWindowInfo = {
	mouse_x: number,
	mouse_y: number,
	window_x: number,
	window_y: number,
	window_width: number,
	window_height: number,
	rel_x: number,
	rel_y: number,
	pixel_ratio: number | null,
};

export type Music = {
	occurrence_id?: string,
	name: string,
	alias: string,
	group: Group,
	canonical_music_id: string,
	url: string,
	path: string | null,
	start_ms: number,
	end_ms: number,
	liked: boolean,
	loudness_profile?: LoudnessProfile | null,
};

export type NowPlayingTrackChangedEvent = {
	session_generation: number,
	playlist_name: string,
	music_name: string,
	canonical_music_id: string,
	music_url: string,
	file_path: string,
	start_ms: number,
	end_ms: number,
	liked: boolean,
};

export type NowPlayingTrackLikedChangedEvent = {
	session_generation: number,
	playlist_name: string,
	canonical_music_id: string,
	liked: boolean,
};

export type PastedDownloadUrlResolution = {
	status: PastedDownloadUrlResolutionStatus,
	url: string | null,
	error: string | null,
	collection: Collection | null,
};

export type PastedDownloadUrlResolutionStatus = "invalid_url" | "existing_collection" | "new_url";

export type PlayList = {
	name: string,
	collections: Collection[],
	groups: Group[],
	extra: Music[],
	created_at: AutoFill,
};

export type PlayListConfigView = {
	name: string,
	collections: CollectionSurfaceView[],
	groups: GroupSurfaceView[],
	extra: Music[],
	created_at: AutoFill,
};

export type PlayListListView = {
	name: string,
	created_at: AutoFill,
};

/**
 *  Behavior:
 *    Playlist write requests carry UI-selected library refs, not stored
 *    collection/group rows. The playlist repository owns the projection from
 *    these refs to canonical record ids and rejects missing refs explicitly.
 * 
 *  Core invariants:
 *    - UI code cannot construct `Group.collection`; that evidence belongs to
 *      the persisted `Collection -> include -> Group` graph.
 *    - Cache, fallback, and draft surfaces are not allowed to materialize
 *      stable playlist storage rows.
 *    - Repeating the same request resolves to the same referenced records.
 */
export type PlayListWriteRequest = {
	name: string,
	collections: PlaylistCollectionRef[],
	groups: PlaylistGroupRef[],
	extra: Music[],
	created_at: AutoFill,
};

export type PlayPlaylistSession = {
	status: PlayPlaylistSessionStatus,
	playlist_name: string,
	session_generation: number | null,
	track_count: number,
	initial_track: PlaybackTrackPayload | null,
};

export type PlayPlaylistSessionStatus = "started" | "pending_first_track" | "superseded";

export type PlaybackAudioVisualizationFrameEvent = {
	session_generation: number,
	playlist_name: string,
	music_name: string,
	canonical_music_id: string,
	music_url: string,
	file_path: string,
	current_position_ms: number,
	range_start_ms: number,
	range_end_ms: number,
	range_progress: number | null,
	playing: boolean,
	paused: boolean,
	loudness_energy: number | null,
	presence: number | null,
	dynamics: number | null,
};

export type PlaybackContinuationMode = "random" | "repeatCurrent";

export type PlaybackDiagnosticTraceDetail = {
	key: string,
	value: string,
};

export type PlaybackDiagnosticTraceEvent = {
	event: string,
	playlist_name: string | null,
	music_name: string | null,
	music_url: string | null,
	start_ms: number | null,
	end_ms: number | null,
	elapsed_ms: number | null,
	candidate_count: number | null,
	queue_count: number | null,
	status: string | null,
	error: string | null,
	details: PlaybackDiagnosticTraceDetail[] | null,
};

export type PlaybackExcludeCommittedEvent = {
	exclude: Exclude,
	exclude_availability: ExcludeAvailability,
};

export type PlaybackStatusPayload = {
	path: string | null,
	playing: boolean,
	paused: boolean,
	position_ms: number,
	duration_ms: number | null,
	playlist_name: string | null,
	music_url: string | null,
	track_start_ms: number | null,
	track_end_ms: number | null,
	playback_start_ms: number | null,
	playback_end_ms: number | null,
};

export type PlaybackSurfaceStatus = "preparing";

export type PlaybackSurfaceStatusChangedEvent = {
	session_generation: number,
	playlist_name: string,
	status: PlaybackSurfaceStatus,
};

export type PlaybackTrackPayload = {
	playlist_name: string,
	music_name: string,
	canonical_music_id: string,
	music_url: string,
	file_path: string,
	start_ms: number,
	end_ms: number,
	liked: boolean,
	loudness_profile?: LoudnessProfile | null,
};

export type PlaylistCollectionRef = {
	name: string,
	url: string,
	folder: string,
	last_updated: string,
	enable_updates: boolean | null,
};

export type PlaylistGroupRef = {
	name: string,
	url: string,
	folder: string,
};

export type RemoteShareStatus = {
	enabled: boolean,
	code: string,
};

export type RemoveExcludeResult = {
	removed: boolean,
	exclude_availability: ExcludeAvailability,
};

export type SpectrumMusicContext = {
	file_musics: Music[],
	source: SpectrumMusicSourceContext | null,
};

export type SpectrumMusicSourceContext = {
	source_collection_url: string,
	source_end_ms: number,
	source_group: Group,
	source_path: string | null,
	source_start_ms: number,
	source_url: string,
};

export type SpectrumPlaybackLoopSignalPayload = {
	track: PlaybackTrackPayload,
	start_ms: number,
	end_ms: number,
};

export type TrackWaveform = {
	sample_rate: number,
	samples_per_point: number,
	points_per_second: number,
	start_ms: number,
	duration_ms: number,
	peaks: WaveformPeak[],
};

export type TrackWaveformSummary = {
	cache_key: string,
	sample_rate: number,
	samples_per_point: number,
	base_points_per_second: number,
	chunk_duration_ms: number,
	start_ms: number,
	duration_ms: number,
	levels: number[],
};

export type TrackWaveformTile = {
	start_px: number,
	width_px: number,
	points_per_second: number,
	min: number[],
	max: number[],
};

export type WaveformPeak = {
	min: number | null,
	max: number | null,
};

export type WindowKindInfo = {
	window: WindowName | null,
	label: string,
	is_primary_window: boolean,
	is_user_window: boolean,
	is_prepared_window: boolean,
};

export type WindowName = "Main" | "Support";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

